--- 
clone: 
  depth: 1
kind: pipeline
name: azrimPipeline
steps: 
  - 
    environment: 
      TG_TOKEN: 
        from_secret: TOKEN
      CHANNEL_ID:
        from_secret: CHATID
    commands: 
      - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
      - pacman -Sy && pacman -S git bc inetutils python2 zip jdk-openjdk lld --noconfirm
      - "curl https://raw.githubusercontent.com/azrim/script/master/kernel/buildnojava | bash"
    image: archlinux:base-devel
    name: Build
    trigger: 
      branch: 
        - staging
