--- 
clone: 
  depth: 1
kind: pipeline
name: azrimPipeline
steps: 
  - 
    environment: 
      TG_TOKEN: 
        from_secret: TOKEN
      CHANNEL_ID:
        from_secret: CHATID
    commands: 
      - "curl https://raw.githubusercontent.com/azrim/script/master/kernel/build | bash"
    image: fadlyas/kernel_dockerfile:latest
    name: Build
    trigger: 
      branch: 
        - FBK
